version: "3.9"
services:
ollama:
image: ollama/ollama:latest
ports:
- "11434:11434"
volumes:
- ollama_models:/root/.ollama
restart: unless-stopped


api:
build:
context: .
dockerfile: Dockerfile.api
environment:
- RAG_DB_PATH=/app/rag_db
- DATA_DIR=/app/data
- OLLAMA_HOST=http://ollama:11434
- OLLAMA_MODEL=llama3.1
- RERANK_ENABLED=1
- DEBUG_CONTEXTS=0
volumes:
- rag_db:/app/rag_db
- data:/app/data
ports:
- "8000:8000"
depends_on:
- ollama
restart: unless-stopped


web:
image: nginx:alpine
volumes:
- ./web:/usr/share/nginx/html:ro
ports:
- "8080:80"
depends_on:
- api
restart: unless-stopped


volumes:
ollama_models:
rag_db:
data: